#!/bin/bash
# These aliases were generated via ~/.dotfiles/git/aliases.zsh.
# Edit that file to make changes to these aliases!
alias gac="git add . && git commit -am"
alias gdr="fn() { git diff $1^..$1; }; fn"
alias glc="fn() { git ll $1^..$1; }; fn"
alias gfl="git log -u"
alias gun="git reset --soft HEAD^"
alias gls="git log --pretty='format:%C(yellow)%h%Cred%d %Creset%s%Cblue [%cn]' --decorate"
alias gld="git log --pretty='format:%C(yellow)%h %ad%Cred%d %Creset%s%Cblue [%cn]' --decorate --date=relative"
alias glg="git log --color --graph"
alias gll="git log --pretty='format:%C(yellow)%h%Cred%d %Creset%s%Cblue [%cn]' --decorate --numstat"
alias gdl="git ll -1"
alias gdlc="git diff --cached HEAD^"
alias gfall="git fetch --all -p"
alias gf="git ls-files | grep -i"
alias ggr="git grep -Ii"
alias gla="git config -l | grep alias | cut -c 7-"
alias gga="git la | grep"
alias gours="fn() { git checkout --ours $@ && git add $@; }; fn"
alias gtheirs="fn() { git checkout --theirs $@ && git add $@; }; fn"
alias gsl="git stash list"
alias gsa="git stash apply"
alias gss="git stash save"
alias gunstash="git stash pop"
alias gr="git reset"
alias gr1="git reset HEAD^"
alias gr2="git reset HEAD^^"
alias grh="git reset --hard"
alias grh1="git reset HEAD^ --hard"
alias grh2="git reset HEAD^^ --hard"
alias gc="git cz"
alias gca="git cz --amend"
alias gco="git checkout"
alias gd="git diff"
alias gs="git status"
alias gsb="git status -sb"
alias ga="git add"
alias gb="git branch"
alias gh="git open"
alias gp="git push"
