DEFAULT_USER='kmarnett'
DOTFILES=$HOME/.dotfiles

APP_SETTINGS_BACKUP_PATH=$HOME/Dropbox
APP_SETTINGS_BACKUP_DIR='app-settings'

ICON_FAILURE="❌ "
ICON_SUCCESS="✅ "
ICON_WARNING="⚠️ "
ICON_INFO="ℹ️ "
