tap "homebrew/bundle"
tap "romkatv/powerlevel10k"
brew "antigen"
brew "python@3.11"
brew "awscli"
brew "ccat"
brew "chroma"
brew "cmake"
brew "coreutils"
brew "eza"
brew "ffmpeg"
brew "findutils"
brew "gimme-aws-creds"
brew "git-delta"
brew "imagemagick"
brew "mackup"
brew "mas"
brew "moreutils"
brew "openssl@1.1"
brew "powerlevel10k"
brew "speedtest-cli"
brew "wifi-password"
brew "yarn"
brew "yt-dlp"
brew "z"
cask "1password"
cask "1password-cli"
cask "dropbox"
cask "figma"
cask "google-chrome"
cask "imageoptim"
cask "iterm2"
cask "kap"
cask "keycastr"
cask "microsoft-auto-update"
cask "microsoft-outlook"
cask "microsoft-teams"
cask "notion"
cask "rectangle"
cask "responsively"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "zoom"
mas "Contrast", id: 1254981365
mas "DaisyDisk", id: 411643860
mas "Data Jar", id: 1453273600
mas "GarageBand", id: 682658836
mas "Hand Mirror", id: 1502839586
mas "Hidden Bar", id: 1452453066
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft PowerPoint", id: 462062816
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Presentify", id: 1507246666
mas "Pure Paste", id: 1611378436
vscode "dsznajder.es7-react-js-snippets"
vscode "esbenp.prettier-vscode"
vscode "figma.figma-vscode-extension"
vscode "formulahendry.auto-rename-tag"
vscode "github.vscode-github-actions"
vscode "mjmlio.vscode-mjml"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.live-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "platformio.platformio-ide"
vscode "redhat.vscode-xml"
vscode "robbowen.synthwave-vscode"
vscode "unifiedjs.vscode-mdx"
vscode "webhint.vscode-webhint"
vscode "xyc.vscode-mdx-preview"
